CREATE TABLE Sheet1(--_Companies VARCHAR(10));
INSERT INTO Sheet1 (--_Companies) VALUES 
('CREATE TABLE companies ('),
('    id INTEGER PRIMARY KEY,'),
('    name TEXT NOT NULL,'),
('    entity_type TEXT CHECK(entity_type IN ('C-corp', 'S-corp', 'LLC')),'),
('    founded_year INTEGER,'),
('    cash REAL DEFAULT 0,'),
('    total_debt REAL DEFAULT 0,'),
('    revenue_annual REAL DEFAULT 0,'),
('    ebitda_annual REAL DEFAULT 0,'),
('    net_income REAL DEFAULT 0,'),
('    dscr REAL DEFAULT 0,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- Employees'),
('CREATE TABLE employees ('),
('    id INTEGER PRIMARY KEY,'),
('    company_id INTEGER REFERENCES companies(id),'),
('    name TEXT NOT NULL,'),
('    role TEXT NOT NULL,'),
('    salary REAL DEFAULT 0,'),
('    hourly_wage REAL,'),
('    hire_date DATE,'),
('    trust_score INTEGER DEFAULT 50 CHECK(trust_score BETWEEN 0 AND 100),'),
('    last_interaction DATE,'),
('    grievances TEXT,'),
('    promises TEXT,'),
('    is_active BOOLEAN DEFAULT 1'),
(');'),
('-- Relationships (NPC memory)'),
('CREATE TABLE relationships ('),
('    id INTEGER PRIMARY KEY,'),
('    entity_name TEXT NOT NULL UNIQUE,'),
('    entity_type TEXT CHECK(entity_type IN ('person', 'organization', 'object')),'),
('    trust_score INTEGER DEFAULT 50,'),
('    last_interaction DATE,'),
('    key_facts TEXT, -- JSON array of memory strings'),
('    promises_made TEXT,'),
('    promises_broken INTEGER DEFAULT 0,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- Financial Snapshots (quarterly)'),
('CREATE TABLE financials ('),
('    id INTEGER PRIMARY KEY,'),
('    company_id INTEGER REFERENCES companies(id),'),
('    year INTEGER,'),
('    quarter INTEGER,'),
('    revenue REAL,'),
('    cogs_opex REAL,'),
('    ebitda REAL,'),
('    depreciation REAL,'),
('    ebit REAL,'),
('    interest REAL,'),
('    taxable_income REAL,'),
('    tax REAL,'),
('    net_income REAL,'),
('    cash REAL,'),
('    total_debt REAL,'),
('    dscr REAL,'),
('    dividend_paid REAL,'),
('    capex REAL,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- Events (everything that happened)'),
('CREATE TABLE events ('),
('    id INTEGER PRIMARY KEY,'),
('    year INTEGER,'),
('    quarter INTEGER,'),
('    event_type TEXT CHECK(event_type IN ('market', 'personnel', 'equipment', 'regulatory', 'financial', 'personal')),'),
('    description TEXT NOT NULL,'),
('    entities_involved TEXT, -- JSON array'),
('    financial_impact REAL DEFAULT 0,'),
('    narrative_rendered TEXT,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- Decisions (player choices)'),
('CREATE TABLE decisions ('),
('    id INTEGER PRIMARY KEY,'),
('    year INTEGER,'),
('    quarter INTEGER,'),
('    decision_text TEXT NOT NULL,'),
('    outcome TEXT,'),
('    financial_impact REAL DEFAULT 0,'),
('    entities_affected TEXT,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- Narrative Log'),
('CREATE TABLE narrative_log ('),
('    id INTEGER PRIMARY KEY,'),
('    year INTEGER,'),
('    quarter INTEGER,'),
('    context TEXT,'),
('    narrative_text TEXT NOT NULL,'),
('    entities_involved TEXT,'),
('    importance INTEGER DEFAULT 5,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- LLM Context (condensed memory blocks)'),
('CREATE TABLE llm_context ('),
('    id INTEGER PRIMARY KEY,'),
('    context_type TEXT CHECK(context_type IN ('character', 'event', 'object', 'promise', 'financial', 'market')),'),
('    content TEXT NOT NULL,'),
('    entities TEXT, -- JSON array'),
('    year INTEGER,'),
('    importance INTEGER DEFAULT 5,'),
('    decay_rate INTEGER DEFAULT 1,'),
('    last_accessed TIMESTAMP,'),
('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- Web Search Cache'),
('CREATE TABLE search_cache ('),
('    id INTEGER PRIMARY KEY,'),
('    query TEXT NOT NULL UNIQUE,'),
('    results TEXT, -- JSON'),
('    cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'),
('    expires_at TIMESTAMP'),
(');'),
('-- BBTW Vending (your SKU)'),
('CREATE TABLE revenue_streams ('),
('    id INTEGER PRIMARY KEY,'),
('    company_id INTEGER REFERENCES companies(id),'),
('    sku TEXT,'),
('    description TEXT,'),
('    monthly_revenue REAL DEFAULT 0,'),
('    monthly_cogs REAL DEFAULT 0,'),
('    is_active BOOLEAN DEFAULT 1'),
(');');